version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8081:8081
    expose:
      - 8081
    volumes:
      - './logs:/var/log/apache2'